/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modal.bean.Produto;
import model.dao.ProdutoDao;

/**
 *
 * @author Marcelo
 */
public class TelaCadProd extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadProd
     */
    public TelaCadProd() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tbCadProd.getModel();
        tbCadProd.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) tbCadProd.getModel();
        modelo.setNumRows(0);

        ProdutoDao pdao = new ProdutoDao();

        for (Produto p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getReferencia(),
                p.getDescricao(),
                p.getPreco(),
                p.getTipo()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProdRef = new javax.swing.JTextField();
        txtProdDesc = new javax.swing.JTextField();
        txtProdPreco = new javax.swing.JTextField();
        cboProdTipo = new javax.swing.JComboBox<>();
        btnProdCad = new javax.swing.JButton();
        btnProdAlt = new javax.swing.JButton();
        btnProdExc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCadProd = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Produtos");
        setPreferredSize(new java.awt.Dimension(1080, 640));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Produto"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Referência:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Descrição: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Preço:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tipo:");

        cboProdTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aplique", "Enfeite", "Sapatinho" }));

        btnProdCad.setText("Cadastrar");
        btnProdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProd(evt);
            }
        });

        btnProdAlt.setText("Atualizar");
        btnProdAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarProd(evt);
            }
        });

        btnProdExc.setText("Excluir");
        btnProdExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirProd(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnProdCad)
                        .addGap(35, 35, 35)
                        .addComponent(btnProdAlt)
                        .addGap(35, 35, 35)
                        .addComponent(btnProdExc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtProdRef, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtProdPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboProdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnProdAlt, btnProdCad, btnProdExc});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboProdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdCad)
                    .addComponent(btnProdAlt)
                    .addComponent(btnProdExc))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnProdAlt, btnProdCad, btnProdExc});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        tbCadProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Referência", "Descrição", "Preço", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCadProd.setRequestFocusEnabled(false);
        tbCadProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCadProdMouseClicked(evt);
            }
        });
        tbCadProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbCadProdKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbCadProd);
        if (tbCadProd.getColumnModel().getColumnCount() > 0) {
            tbCadProd.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        setBounds(0, 0, 1080, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarProd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProd
        // Cadastra os produtos:

        Produto p = new Produto();
        ProdutoDao dao = new ProdutoDao();
        
        p.setReferencia(txtProdRef.getText());
        p.setDescricao(txtProdDesc.getText());
        p.setPreco(Float.parseFloat(txtProdPreco.getText()));
        p.setTipo(cboProdTipo.getSelectedItem().toString());
        dao.create(p);

        txtProdRef.setText("");
        txtProdDesc.setText("");
        txtProdPreco.setText("");

        readJTable();

    }//GEN-LAST:event_CadastrarProd

    private void tbCadProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCadProdMouseClicked
        // TODO add your handling code here:

        if (tbCadProd.getSelectedRow() != -1) {
            txtProdRef.setText(tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 1).toString());
            txtProdDesc.setText(tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 2).toString());
            txtProdPreco.setText(tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 3).toString());
            cboProdTipo.setSelectedItem(tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 4));
        }
    }//GEN-LAST:event_tbCadProdMouseClicked

    private void tbCadProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbCadProdKeyReleased
        // TODO add your handling code here:

        if (tbCadProd.getSelectedRow() != -1) {
            txtProdRef.setText(tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 1).toString());
            txtProdDesc.setText(tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 2).toString());
            txtProdPreco.setText(tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 3).toString());
            cboProdTipo.setSelectedItem(tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 4));
        }
    }//GEN-LAST:event_tbCadProdKeyReleased

    private void AtualizarProd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarProd
        // Atualiza os Produtos:

        if (tbCadProd.getSelectedRow() != -1) {

            Produto p = new Produto();
            ProdutoDao dao = new ProdutoDao();
            
            p.setId((int)tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 0));
            p.setReferencia(txtProdRef.getText());
            p.setDescricao(txtProdDesc.getText());
            p.setPreco(Float.parseFloat(txtProdPreco.getText()));
            p.setTipo(cboProdTipo.getSelectedItem().toString());
            dao.update(p);

            txtProdRef.setText("");
            txtProdDesc.setText("");
            txtProdPreco.setText("");

            readJTable();
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar.");
        }
        
    }//GEN-LAST:event_AtualizarProd

    private void ExcluirProd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirProd
        // Exclui os Produtos:
        
        if (tbCadProd.getSelectedRow() != -1) {

            Produto p = new Produto();
            ProdutoDao dao = new ProdutoDao();
            
            p.setId((int)tbCadProd.getValueAt(tbCadProd.getSelectedRow(), 0));
            dao.delete(p);

            txtProdRef.setText("");
            txtProdDesc.setText("");
            txtProdPreco.setText("");

            readJTable();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
        
    }//GEN-LAST:event_ExcluirProd


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdAlt;
    private javax.swing.JButton btnProdCad;
    private javax.swing.JButton btnProdExc;
    private javax.swing.JComboBox<String> cboProdTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCadProd;
    private javax.swing.JTextField txtProdDesc;
    private javax.swing.JTextField txtProdPreco;
    private javax.swing.JTextField txtProdRef;
    // End of variables declaration//GEN-END:variables
}
